spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_DATABASE_URL}
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  servlet:
    multipart:  # 파일 올리는 설정
      max-file-size: 50MB # 요청한 파일 한 개의 크기
      max-request-size: 50MB # 요청한 파일 전체의 크기
  redis:
    host: ${LOCAL_REDIS_HOST}
    port: ${LOCAL_REDIS_PORT}
    password: ${LOCAL_REDIS_PASSWORD}
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: default

logging:
  level:
    com.galaxy.gunpang: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    context-path: /api
  port:
    8080


springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui
  default-consumes-media-type:
    - application/json;charset=UTF-8
    - application/x-www-form-urlencoded
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true

jwt:
  secret: ${JWT_SECRET}
